Mobile Portfolio pull request  number 2
Ashuaks/Portfolio pull request #2
Opened 2022-07-07 16:56 UTC by Ashuaks

The second milestone of the project "Portfolio setup and mobile version skeleton".
In this, I created the middle section of the Figma portfolio template 1.

2022-07-07 17:23 UTC, danmainah requested changes
Hi @Ashuaks , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter errors
✔️ Github flow was correctly used
✔️  Good design


# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-07-07 17:23 UTC, danmainah commented on index.html
> +        <div class="cards">
- [ ] Kindly ensure your work section is wrapped using the `<section>` tag, currently you are using a `div`.

2022-07-07 17:23 UTC, danmainah commented on index.html
> +                <button type="button" class="btn see-projects">See Projects</button>
- [x] Kindly add a hover effect on your buttons, ensure to use the recommended style below is a snippet of the format:

![image](https://user-images.githubusercontent.com/61408860/177832473-e2ddf052-68b8-488b-93c0-79ce93821221.png)

2022-07-07 17:23 UTC, danmainah commented on index.html
> +        <div class="about_myself_section">
- [x] Kindly ensure your about section is wrapped using a `section` tag, please replace the div tag with the section tag.

2022-07-07 17:23 UTC, danmainah commented on index.html
> +                <p class="about_lets">LETS CONNECT</p>
- [ ] Kindy use the `hx` tag for this line because let's connect is supposed to be a title.

2022-07-09 07:57 UTC, wuletawwonte approved these changes
## STATUS: APPROVED ♻️♻️
Hi @Ashuaks  👋🏿👋🏿👋🏿, 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀  
Congratulations! 🎉 

![approve](https://user-images.githubusercontent.com/12524453/177408688-113768c1-53d0-4c38-9027-f3a87bd35cdb.gif)

## TO HIGHLIGHT: 
- Your project is professional ✔️ 
- Correct Github Flow ✔️
- Your PR has a proper title and description ✔️
- Well structured files ✔️ 

## Required Changes ♻️
_Please check the comments under the review as well._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-07-09 07:57 UTC, wuletawwonte commented on index.html
> +        <div class="about_myself_section">
- [ ] [OPTIONAL] Please wrap each section in `section` tag instead of `div` tags. That would make the code semantically correct.

2022-07-09 08:06 UTC, merged